name: Auto Format

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      CI: true
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore MultiplayerHelper.csproj
    
    - name: Format C# code
      run: dotnet format MultiplayerHelper.csproj --verbosity minimal
      continue-on-error: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install Prettier
      run: npm install -g prettier
    
    - name: Format other files with Prettier
      run: prettier --write --ignore-unknown . --ignore-path .prettierignore
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "formatted=false" >> $GITHUB_OUTPUT
        else
          echo "formatted=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit formatting changes
      if: steps.changes.outputs.formatted == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "style: format code"
        git push